### PR TITLE
Added toggle to view raw program instruction logs for transactions

### PR DESCRIPTION
**Pull request by bryantanjw**
#### Problem
User wants to view a transaction's raw program instruction logs for debugging purposes. [#23784](https://github.com/solana-labs/solana/issues/23784)

#### Summary of Changes
Added `<> Raw` toggle to Program Instruction Logs

### CODE REVIEW

**Comment by ngundotra** [comment]
@bryantanjw @nixxholas @BingHuang-Chin Can you slim this PR down to *only* have the parse logs changes? Otw looks good to me

**Comment by ngundotra** [comment]
Oh wait, my bad, wrong repo! xD

**Comment by nixxholas** [comment]
> Oh wait, my bad, wrong repo! xD

All good! Is it possible to re-open the PR on the monorepo?

**Comment by ngundotra** [comment]
@nixxholas is it possible to open a separate PR in the monorepo with only the parseLogs changes from this PR? Want to make sure y'all get credit for this stuff

**Pull request closed without merging**
